package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblAlgorithm generated by hbm2java
 */
@Entity
@Table(name="tbl_algorithm"
    ,catalog="db_manager"
)
public class TblAlgorithm  implements java.io.Serializable {


     private String txtId;
     private TblTechnology tblTechnology;
     private String txtDeptId;
     private String txtProjectCategory;
     private String txtAlgorithmName;
     private String txtAbstract;
     private String txtRemark;
     private String txtPdf;
     private String txtPpt;
     private String txtDoc;
     private char txtIsActive;

    public TblAlgorithm() {
    }

	
    public TblAlgorithm(String txtId, TblTechnology tblTechnology, String txtDeptId, char txtIsActive) {
        this.txtId = txtId;
        this.tblTechnology = tblTechnology;
        this.txtDeptId = txtDeptId;
        this.txtIsActive = txtIsActive;
    }
    public TblAlgorithm(String txtId, TblTechnology tblTechnology, String txtDeptId, String txtProjectCategory, String txtAlgorithmName, String txtAbstract, String txtRemark, String txtPdf, String txtPpt, String txtDoc, char txtIsActive) {
       this.txtId = txtId;
       this.tblTechnology = tblTechnology;
       this.txtDeptId = txtDeptId;
       this.txtProjectCategory = txtProjectCategory;
       this.txtAlgorithmName = txtAlgorithmName;
       this.txtAbstract = txtAbstract;
       this.txtRemark = txtRemark;
       this.txtPdf = txtPdf;
       this.txtPpt = txtPpt;
       this.txtDoc = txtDoc;
       this.txtIsActive = txtIsActive;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="txtCategoryId", nullable=false)
    public TblTechnology getTblTechnology() {
        return this.tblTechnology;
    }
    
    public void setTblTechnology(TblTechnology tblTechnology) {
        this.tblTechnology = tblTechnology;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtProjectCategory", length=50)
    public String getTxtProjectCategory() {
        return this.txtProjectCategory;
    }
    
    public void setTxtProjectCategory(String txtProjectCategory) {
        this.txtProjectCategory = txtProjectCategory;
    }

    
    @Column(name="txtAlgorithmName", length=50)
    public String getTxtAlgorithmName() {
        return this.txtAlgorithmName;
    }
    
    public void setTxtAlgorithmName(String txtAlgorithmName) {
        this.txtAlgorithmName = txtAlgorithmName;
    }

    
    @Column(name="txtAbstract", length=65535)
    public String getTxtAbstract() {
        return this.txtAbstract;
    }
    
    public void setTxtAbstract(String txtAbstract) {
        this.txtAbstract = txtAbstract;
    }

    
    @Column(name="txtRemark", length=500)
    public String getTxtRemark() {
        return this.txtRemark;
    }
    
    public void setTxtRemark(String txtRemark) {
        this.txtRemark = txtRemark;
    }

    
    @Column(name="txtPDF", length=500)
    public String getTxtPdf() {
        return this.txtPdf;
    }
    
    public void setTxtPdf(String txtPdf) {
        this.txtPdf = txtPdf;
    }

    
    @Column(name="txtPPT", length=500)
    public String getTxtPpt() {
        return this.txtPpt;
    }
    
    public void setTxtPpt(String txtPpt) {
        this.txtPpt = txtPpt;
    }

    
    @Column(name="txtDOC", length=500)
    public String getTxtDoc() {
        return this.txtDoc;
    }
    
    public void setTxtDoc(String txtDoc) {
        this.txtDoc = txtDoc;
    }

    
    @Column(name="txtIsActive", nullable=false, length=1)
    public char getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(char txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


