package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblEmployee generated by hbm2java
 */
@Entity
@Table(name="tbl_employee"
    ,catalog="db_manager"
)
public class TblEmployee  implements java.io.Serializable {


     private String txtId;
     private String txtDeptId;
     private String txtEmpName;
     private String txtEmpEmail;
     private String txtPhoneNo;
     private String txtMobileNo;
     private String txtPassword;
     private String txtEmployeeRole;
     private Character txtIsActive;

    public TblEmployee() {
    }

	
    public TblEmployee(String txtId, String txtDeptId) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
    }
    public TblEmployee(String txtId, String txtDeptId, String txtEmpName, String txtEmpEmail, String txtPhoneNo, String txtMobileNo, String txtPassword, String txtEmployeeRole, Character txtIsActive) {
       this.txtId = txtId;
       this.txtDeptId = txtDeptId;
       this.txtEmpName = txtEmpName;
       this.txtEmpEmail = txtEmpEmail;
       this.txtPhoneNo = txtPhoneNo;
       this.txtMobileNo = txtMobileNo;
       this.txtPassword = txtPassword;
       this.txtEmployeeRole = txtEmployeeRole;
       this.txtIsActive = txtIsActive;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtEmpName", length=50)
    public String getTxtEmpName() {
        return this.txtEmpName;
    }
    
    public void setTxtEmpName(String txtEmpName) {
        this.txtEmpName = txtEmpName;
    }

    
    @Column(name="txtEmpEmail", length=50)
    public String getTxtEmpEmail() {
        return this.txtEmpEmail;
    }
    
    public void setTxtEmpEmail(String txtEmpEmail) {
        this.txtEmpEmail = txtEmpEmail;
    }

    
    @Column(name="txtPhoneNo", length=15)
    public String getTxtPhoneNo() {
        return this.txtPhoneNo;
    }
    
    public void setTxtPhoneNo(String txtPhoneNo) {
        this.txtPhoneNo = txtPhoneNo;
    }

    
    @Column(name="txtMobileNo", length=15)
    public String getTxtMobileNo() {
        return this.txtMobileNo;
    }
    
    public void setTxtMobileNo(String txtMobileNo) {
        this.txtMobileNo = txtMobileNo;
    }

    
    @Column(name="txtPassword", length=15)
    public String getTxtPassword() {
        return this.txtPassword;
    }
    
    public void setTxtPassword(String txtPassword) {
        this.txtPassword = txtPassword;
    }

    
    @Column(name="txtEmployeeRole", length=15)
    public String getTxtEmployeeRole() {
        return this.txtEmployeeRole;
    }
    
    public void setTxtEmployeeRole(String txtEmployeeRole) {
        this.txtEmployeeRole = txtEmployeeRole;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


