package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblGroupQueries generated by hbm2java
 */
@Entity
@Table(name="tbl_group_queries"
    ,catalog="db_manager"
)
public class TblGroupQueries  implements java.io.Serializable {


     private String txtId;
     private TblProject tblProject;
     private TblProjectGroup tblProjectGroup;
     private String txtDeptId;
     private Date txtEnteryDate;
     private String txtQuery;
     private String txtAttachment1;
     private Character txtIsActive;
     private Set<TblGroupQueriesAnswer> tblGroupQueriesAnswers = new HashSet<TblGroupQueriesAnswer>(0);

    public TblGroupQueries() {
    }

	
    public TblGroupQueries(String txtId, String txtDeptId) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
    }
    public TblGroupQueries(String txtId, TblProject tblProject, TblProjectGroup tblProjectGroup, String txtDeptId, Date txtEnteryDate, String txtQuery, String txtAttachment1, Character txtIsActive, Set<TblGroupQueriesAnswer> tblGroupQueriesAnswers) {
       this.txtId = txtId;
       this.tblProject = tblProject;
       this.tblProjectGroup = tblProjectGroup;
       this.txtDeptId = txtDeptId;
       this.txtEnteryDate = txtEnteryDate;
       this.txtQuery = txtQuery;
       this.txtAttachment1 = txtAttachment1;
       this.txtIsActive = txtIsActive;
       this.tblGroupQueriesAnswers = tblGroupQueriesAnswers;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="txtProjectId")
    public TblProject getTblProject() {
        return this.tblProject;
    }
    
    public void setTblProject(TblProject tblProject) {
        this.tblProject = tblProject;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="txtGroupId")
    public TblProjectGroup getTblProjectGroup() {
        return this.tblProjectGroup;
    }
    
    public void setTblProjectGroup(TblProjectGroup tblProjectGroup) {
        this.tblProjectGroup = tblProjectGroup;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtEnteryDate", length=19)
    public Date getTxtEnteryDate() {
        return this.txtEnteryDate;
    }
    
    public void setTxtEnteryDate(Date txtEnteryDate) {
        this.txtEnteryDate = txtEnteryDate;
    }

    
    @Column(name="txtQuery", length=65535)
    public String getTxtQuery() {
        return this.txtQuery;
    }
    
    public void setTxtQuery(String txtQuery) {
        this.txtQuery = txtQuery;
    }

    
    @Column(name="txtAttachment1", length=65535)
    public String getTxtAttachment1() {
        return this.txtAttachment1;
    }
    
    public void setTxtAttachment1(String txtAttachment1) {
        this.txtAttachment1 = txtAttachment1;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblGroupQueries")
    public Set<TblGroupQueriesAnswer> getTblGroupQueriesAnswers() {
        return this.tblGroupQueriesAnswers;
    }
    
    public void setTblGroupQueriesAnswers(Set<TblGroupQueriesAnswer> tblGroupQueriesAnswers) {
        this.tblGroupQueriesAnswers = tblGroupQueriesAnswers;
    }




}


