package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblGroupSchedules generated by hbm2java
 */
@Entity
@Table(name="tbl_group_schedules"
    ,catalog="db_manager"
)
public class TblGroupSchedules  implements java.io.Serializable {


     private String txtId;
     private TblProjectGroup tblProjectGroup;
     private String txtDeptId;
     private Date txtSchedulesDate;
     private String txtSchedulesTopic;
     private String txtDiscussionTime;
     private String txtTeacherName;
     private String txtRemark;
     private char txtIsCancled;
     private Character txtIsActive;

    public TblGroupSchedules() {
    }

	
    public TblGroupSchedules(String txtId, String txtDeptId, String txtDiscussionTime, char txtIsCancled) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
        this.txtDiscussionTime = txtDiscussionTime;
        this.txtIsCancled = txtIsCancled;
    }
    public TblGroupSchedules(String txtId, TblProjectGroup tblProjectGroup, String txtDeptId, Date txtSchedulesDate, String txtSchedulesTopic, String txtDiscussionTime, String txtTeacherName, String txtRemark, char txtIsCancled, Character txtIsActive) {
       this.txtId = txtId;
       this.tblProjectGroup = tblProjectGroup;
       this.txtDeptId = txtDeptId;
       this.txtSchedulesDate = txtSchedulesDate;
       this.txtSchedulesTopic = txtSchedulesTopic;
       this.txtDiscussionTime = txtDiscussionTime;
       this.txtTeacherName = txtTeacherName;
       this.txtRemark = txtRemark;
       this.txtIsCancled = txtIsCancled;
       this.txtIsActive = txtIsActive;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="txtGroupId")
    public TblProjectGroup getTblProjectGroup() {
        return this.tblProjectGroup;
    }
    
    public void setTblProjectGroup(TblProjectGroup tblProjectGroup) {
        this.tblProjectGroup = tblProjectGroup;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtSchedulesDate", length=19)
    public Date getTxtSchedulesDate() {
        return this.txtSchedulesDate;
    }
    
    public void setTxtSchedulesDate(Date txtSchedulesDate) {
        this.txtSchedulesDate = txtSchedulesDate;
    }

    
    @Column(name="txtSchedulesTopic", length=500)
    public String getTxtSchedulesTopic() {
        return this.txtSchedulesTopic;
    }
    
    public void setTxtSchedulesTopic(String txtSchedulesTopic) {
        this.txtSchedulesTopic = txtSchedulesTopic;
    }

    
    @Column(name="txtDiscussionTime", nullable=false, length=50)
    public String getTxtDiscussionTime() {
        return this.txtDiscussionTime;
    }
    
    public void setTxtDiscussionTime(String txtDiscussionTime) {
        this.txtDiscussionTime = txtDiscussionTime;
    }

    
    @Column(name="txtTeacherName", length=50)
    public String getTxtTeacherName() {
        return this.txtTeacherName;
    }
    
    public void setTxtTeacherName(String txtTeacherName) {
        this.txtTeacherName = txtTeacherName;
    }

    
    @Column(name="txtRemark", length=50)
    public String getTxtRemark() {
        return this.txtRemark;
    }
    
    public void setTxtRemark(String txtRemark) {
        this.txtRemark = txtRemark;
    }

    
    @Column(name="txtIsCancled", nullable=false, length=1)
    public char getTxtIsCancled() {
        return this.txtIsCancled;
    }
    
    public void setTxtIsCancled(char txtIsCancled) {
        this.txtIsCancled = txtIsCancled;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


