package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblGroupQueriesAnswer generated by hbm2java
 */
@Entity
@Table(name="tbl_group_queries_answer"
    ,catalog="db_manager"
)
public class TblGroupQueriesAnswer  implements java.io.Serializable {


     private String txtId;
     private TblProject tblProject;
     private TblGroupQueries tblGroupQueries;
     private String txtDeptId;
     private String txtGroupId;
     private String txtAnswer;
     private String txtAttachment1;
     private String txtEnteredDate;
     private Character txtIsActive;

    public TblGroupQueriesAnswer() {
    }

	
    public TblGroupQueriesAnswer(String txtId, String txtDeptId, String txtGroupId) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
        this.txtGroupId = txtGroupId;
    }
    public TblGroupQueriesAnswer(String txtId, TblProject tblProject, TblGroupQueries tblGroupQueries, String txtDeptId, String txtGroupId, String txtAnswer, String txtAttachment1, String txtEnteredDate, Character txtIsActive) {
       this.txtId = txtId;
       this.tblProject = tblProject;
       this.tblGroupQueries = tblGroupQueries;
       this.txtDeptId = txtDeptId;
       this.txtGroupId = txtGroupId;
       this.txtAnswer = txtAnswer;
       this.txtAttachment1 = txtAttachment1;
       this.txtEnteredDate = txtEnteredDate;
       this.txtIsActive = txtIsActive;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="txtProjectId")
    public TblProject getTblProject() {
        return this.tblProject;
    }
    
    public void setTblProject(TblProject tblProject) {
        this.tblProject = tblProject;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="txtQueriesId")
    public TblGroupQueries getTblGroupQueries() {
        return this.tblGroupQueries;
    }
    
    public void setTblGroupQueries(TblGroupQueries tblGroupQueries) {
        this.tblGroupQueries = tblGroupQueries;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtGroupId", nullable=false, length=38)
    public String getTxtGroupId() {
        return this.txtGroupId;
    }
    
    public void setTxtGroupId(String txtGroupId) {
        this.txtGroupId = txtGroupId;
    }

    
    @Column(name="txtAnswer", length=65535)
    public String getTxtAnswer() {
        return this.txtAnswer;
    }
    
    public void setTxtAnswer(String txtAnswer) {
        this.txtAnswer = txtAnswer;
    }

    
    @Column(name="txtAttachment1", length=65535)
    public String getTxtAttachment1() {
        return this.txtAttachment1;
    }
    
    public void setTxtAttachment1(String txtAttachment1) {
        this.txtAttachment1 = txtAttachment1;
    }

    
    @Column(name="txtEnteredDate", length=38)
    public String getTxtEnteredDate() {
        return this.txtEnteredDate;
    }
    
    public void setTxtEnteredDate(String txtEnteredDate) {
        this.txtEnteredDate = txtEnteredDate;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


