package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblJobalert generated by hbm2java
 */
@Entity
@Table(name="tbl_jobalert"
    ,catalog="db_manager"
)
public class TblJobalert  implements java.io.Serializable {


     private String txtId;
     private String txtDeptId;
     private String txtCompanyName;
     private String txtExperiance;
     private String txtAddress;
     private Date txtEntryDate;
     private Character txtIsActive;

    public TblJobalert() {
    }

	
    public TblJobalert(String txtId, String txtDeptId, String txtAddress) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
        this.txtAddress = txtAddress;
    }
    public TblJobalert(String txtId, String txtDeptId, String txtCompanyName, String txtExperiance, String txtAddress, Date txtEntryDate, Character txtIsActive) {
       this.txtId = txtId;
       this.txtDeptId = txtDeptId;
       this.txtCompanyName = txtCompanyName;
       this.txtExperiance = txtExperiance;
       this.txtAddress = txtAddress;
       this.txtEntryDate = txtEntryDate;
       this.txtIsActive = txtIsActive;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtCompanyName", length=150)
    public String getTxtCompanyName() {
        return this.txtCompanyName;
    }
    
    public void setTxtCompanyName(String txtCompanyName) {
        this.txtCompanyName = txtCompanyName;
    }

    
    @Column(name="txtExperiance", length=20)
    public String getTxtExperiance() {
        return this.txtExperiance;
    }
    
    public void setTxtExperiance(String txtExperiance) {
        this.txtExperiance = txtExperiance;
    }

    
    @Column(name="txtAddress", nullable=false, length=500)
    public String getTxtAddress() {
        return this.txtAddress;
    }
    
    public void setTxtAddress(String txtAddress) {
        this.txtAddress = txtAddress;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtEntryDate", length=19)
    public Date getTxtEntryDate() {
        return this.txtEntryDate;
    }
    
    public void setTxtEntryDate(Date txtEntryDate) {
        this.txtEntryDate = txtEntryDate;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


