package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblOutsource generated by hbm2java
 */
@Entity
@Table(name="tbl_outsource"
    ,catalog="db_manager"
)
public class TblOutsource  implements java.io.Serializable {


     private String txtId;
     private String txtDeptId;
     private String txtCompanyName;
     private String txtCompanyEmail;
     private String txtCompanyPhoneNo;
     private String txtCompanyMobileNo;
     private String txtCompanyCity;
     private String txtCompanyState;
     private String txtCompanyAddress;
     private String txtCompanyLandMark;
     private String txtCompanyPinCode;
     private String txtCompanyFounderName;
     private String txtCompanyFounderEmail;
     private String txtCompanyEmployee;
     private String txtFromIp;
     private Date txtEntryDate;
     private String txtEnteredBy;
     private Date txtUpdateDate;
     private String txtUpdateBy;
     private Character txtIsDelete;
     private Character txtIsActive;

    public TblOutsource() {
    }

	
    public TblOutsource(String txtId, String txtDeptId) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
    }
    public TblOutsource(String txtId, String txtDeptId, String txtCompanyName, String txtCompanyEmail, String txtCompanyPhoneNo, String txtCompanyMobileNo, String txtCompanyCity, String txtCompanyState, String txtCompanyAddress, String txtCompanyLandMark, String txtCompanyPinCode, String txtCompanyFounderName, String txtCompanyFounderEmail, String txtCompanyEmployee, String txtFromIp, Date txtEntryDate, String txtEnteredBy, Date txtUpdateDate, String txtUpdateBy, Character txtIsDelete, Character txtIsActive) {
       this.txtId = txtId;
       this.txtDeptId = txtDeptId;
       this.txtCompanyName = txtCompanyName;
       this.txtCompanyEmail = txtCompanyEmail;
       this.txtCompanyPhoneNo = txtCompanyPhoneNo;
       this.txtCompanyMobileNo = txtCompanyMobileNo;
       this.txtCompanyCity = txtCompanyCity;
       this.txtCompanyState = txtCompanyState;
       this.txtCompanyAddress = txtCompanyAddress;
       this.txtCompanyLandMark = txtCompanyLandMark;
       this.txtCompanyPinCode = txtCompanyPinCode;
       this.txtCompanyFounderName = txtCompanyFounderName;
       this.txtCompanyFounderEmail = txtCompanyFounderEmail;
       this.txtCompanyEmployee = txtCompanyEmployee;
       this.txtFromIp = txtFromIp;
       this.txtEntryDate = txtEntryDate;
       this.txtEnteredBy = txtEnteredBy;
       this.txtUpdateDate = txtUpdateDate;
       this.txtUpdateBy = txtUpdateBy;
       this.txtIsDelete = txtIsDelete;
       this.txtIsActive = txtIsActive;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtCompanyName", length=50)
    public String getTxtCompanyName() {
        return this.txtCompanyName;
    }
    
    public void setTxtCompanyName(String txtCompanyName) {
        this.txtCompanyName = txtCompanyName;
    }

    
    @Column(name="txtCompanyEmail", length=50)
    public String getTxtCompanyEmail() {
        return this.txtCompanyEmail;
    }
    
    public void setTxtCompanyEmail(String txtCompanyEmail) {
        this.txtCompanyEmail = txtCompanyEmail;
    }

    
    @Column(name="txtCompanyPhoneNo", length=15)
    public String getTxtCompanyPhoneNo() {
        return this.txtCompanyPhoneNo;
    }
    
    public void setTxtCompanyPhoneNo(String txtCompanyPhoneNo) {
        this.txtCompanyPhoneNo = txtCompanyPhoneNo;
    }

    
    @Column(name="txtCompanyMobileNo", length=15)
    public String getTxtCompanyMobileNo() {
        return this.txtCompanyMobileNo;
    }
    
    public void setTxtCompanyMobileNo(String txtCompanyMobileNo) {
        this.txtCompanyMobileNo = txtCompanyMobileNo;
    }

    
    @Column(name="txtCompanyCity", length=20)
    public String getTxtCompanyCity() {
        return this.txtCompanyCity;
    }
    
    public void setTxtCompanyCity(String txtCompanyCity) {
        this.txtCompanyCity = txtCompanyCity;
    }

    
    @Column(name="txtCompanyState", length=20)
    public String getTxtCompanyState() {
        return this.txtCompanyState;
    }
    
    public void setTxtCompanyState(String txtCompanyState) {
        this.txtCompanyState = txtCompanyState;
    }

    
    @Column(name="txtCompanyAddress", length=50)
    public String getTxtCompanyAddress() {
        return this.txtCompanyAddress;
    }
    
    public void setTxtCompanyAddress(String txtCompanyAddress) {
        this.txtCompanyAddress = txtCompanyAddress;
    }

    
    @Column(name="txtCompanyLandMark", length=50)
    public String getTxtCompanyLandMark() {
        return this.txtCompanyLandMark;
    }
    
    public void setTxtCompanyLandMark(String txtCompanyLandMark) {
        this.txtCompanyLandMark = txtCompanyLandMark;
    }

    
    @Column(name="txtCompanyPinCode", length=6)
    public String getTxtCompanyPinCode() {
        return this.txtCompanyPinCode;
    }
    
    public void setTxtCompanyPinCode(String txtCompanyPinCode) {
        this.txtCompanyPinCode = txtCompanyPinCode;
    }

    
    @Column(name="txtCompanyFounderName", length=50)
    public String getTxtCompanyFounderName() {
        return this.txtCompanyFounderName;
    }
    
    public void setTxtCompanyFounderName(String txtCompanyFounderName) {
        this.txtCompanyFounderName = txtCompanyFounderName;
    }

    
    @Column(name="txtCompanyFounderEmail", length=50)
    public String getTxtCompanyFounderEmail() {
        return this.txtCompanyFounderEmail;
    }
    
    public void setTxtCompanyFounderEmail(String txtCompanyFounderEmail) {
        this.txtCompanyFounderEmail = txtCompanyFounderEmail;
    }

    
    @Column(name="txtCompanyEmployee", length=38)
    public String getTxtCompanyEmployee() {
        return this.txtCompanyEmployee;
    }
    
    public void setTxtCompanyEmployee(String txtCompanyEmployee) {
        this.txtCompanyEmployee = txtCompanyEmployee;
    }

    
    @Column(name="txtFromIp", length=15)
    public String getTxtFromIp() {
        return this.txtFromIp;
    }
    
    public void setTxtFromIp(String txtFromIp) {
        this.txtFromIp = txtFromIp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtEntryDate", length=19)
    public Date getTxtEntryDate() {
        return this.txtEntryDate;
    }
    
    public void setTxtEntryDate(Date txtEntryDate) {
        this.txtEntryDate = txtEntryDate;
    }

    
    @Column(name="txtEnteredBy", length=38)
    public String getTxtEnteredBy() {
        return this.txtEnteredBy;
    }
    
    public void setTxtEnteredBy(String txtEnteredBy) {
        this.txtEnteredBy = txtEnteredBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtUpdateDate", length=19)
    public Date getTxtUpdateDate() {
        return this.txtUpdateDate;
    }
    
    public void setTxtUpdateDate(Date txtUpdateDate) {
        this.txtUpdateDate = txtUpdateDate;
    }

    
    @Column(name="txtUpdateBy", length=38)
    public String getTxtUpdateBy() {
        return this.txtUpdateBy;
    }
    
    public void setTxtUpdateBy(String txtUpdateBy) {
        this.txtUpdateBy = txtUpdateBy;
    }

    
    @Column(name="txtIsDelete", length=1)
    public Character getTxtIsDelete() {
        return this.txtIsDelete;
    }
    
    public void setTxtIsDelete(Character txtIsDelete) {
        this.txtIsDelete = txtIsDelete;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


