package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblProject generated by hbm2java
 */
@Entity
@Table(name="tbl_project"
    ,catalog="db_manager"
)
public class TblProject  implements java.io.Serializable {


     private String txtId;
     private TblTechnology tblTechnology;
     private String txtDeptId;
     private String txtTechnologyName;
     private String txtProjectName;
     private String txtAbstract;
     private String txtSynopsis;
     private String txtIeee;
     private String txtPpt;
     private String txtVideo;
     private String txtThesis;
     private String txtFlowDiagram;
     private Date txtEntryDate;
     private Character txtIsActive;
     private Set<TblProjectGroup> tblProjectGroups = new HashSet<TblProjectGroup>(0);
     private Set<TblGroupQueriesAnswer> tblGroupQueriesAnswers = new HashSet<TblGroupQueriesAnswer>(0);
     private Set<TblSnapshot> tblSnapshots = new HashSet<TblSnapshot>(0);
     private Set<TblProjectUpdates> tblProjectUpdateses = new HashSet<TblProjectUpdates>(0);
     private Set<TblGroupAccount> tblGroupAccounts = new HashSet<TblGroupAccount>(0);
     private Set<TblGroupQueries> tblGroupQuerieses = new HashSet<TblGroupQueries>(0);

    public TblProject() {
    }

	
    public TblProject(String txtId, TblTechnology tblTechnology, String txtDeptId) {
        this.txtId = txtId;
        this.tblTechnology = tblTechnology;
        this.txtDeptId = txtDeptId;
    }
    public TblProject(String txtId, TblTechnology tblTechnology, String txtDeptId, String txtTechnologyName, String txtProjectName, String txtAbstract, String txtSynopsis, String txtIeee, String txtPpt, String txtVideo, String txtThesis, String txtFlowDiagram, Date txtEntryDate, Character txtIsActive, Set<TblProjectGroup> tblProjectGroups, Set<TblGroupQueriesAnswer> tblGroupQueriesAnswers, Set<TblSnapshot> tblSnapshots, Set<TblProjectUpdates> tblProjectUpdateses, Set<TblGroupAccount> tblGroupAccounts, Set<TblGroupQueries> tblGroupQuerieses) {
       this.txtId = txtId;
       this.tblTechnology = tblTechnology;
       this.txtDeptId = txtDeptId;
       this.txtTechnologyName = txtTechnologyName;
       this.txtProjectName = txtProjectName;
       this.txtAbstract = txtAbstract;
       this.txtSynopsis = txtSynopsis;
       this.txtIeee = txtIeee;
       this.txtPpt = txtPpt;
       this.txtVideo = txtVideo;
       this.txtThesis = txtThesis;
       this.txtFlowDiagram = txtFlowDiagram;
       this.txtEntryDate = txtEntryDate;
       this.txtIsActive = txtIsActive;
       this.tblProjectGroups = tblProjectGroups;
       this.tblGroupQueriesAnswers = tblGroupQueriesAnswers;
       this.tblSnapshots = tblSnapshots;
       this.tblProjectUpdateses = tblProjectUpdateses;
       this.tblGroupAccounts = tblGroupAccounts;
       this.tblGroupQuerieses = tblGroupQuerieses;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="txtProjectCategory", nullable=false)
    public TblTechnology getTblTechnology() {
        return this.tblTechnology;
    }
    
    public void setTblTechnology(TblTechnology tblTechnology) {
        this.tblTechnology = tblTechnology;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtTechnologyName", length=50)
    public String getTxtTechnologyName() {
        return this.txtTechnologyName;
    }
    
    public void setTxtTechnologyName(String txtTechnologyName) {
        this.txtTechnologyName = txtTechnologyName;
    }

    
    @Column(name="txtProjectName", length=500)
    public String getTxtProjectName() {
        return this.txtProjectName;
    }
    
    public void setTxtProjectName(String txtProjectName) {
        this.txtProjectName = txtProjectName;
    }

    
    @Column(name="txtAbstract", length=65535)
    public String getTxtAbstract() {
        return this.txtAbstract;
    }
    
    public void setTxtAbstract(String txtAbstract) {
        this.txtAbstract = txtAbstract;
    }

    
    @Column(name="txtSynopsis", length=500)
    public String getTxtSynopsis() {
        return this.txtSynopsis;
    }
    
    public void setTxtSynopsis(String txtSynopsis) {
        this.txtSynopsis = txtSynopsis;
    }

    
    @Column(name="txtIeee", length=500)
    public String getTxtIeee() {
        return this.txtIeee;
    }
    
    public void setTxtIeee(String txtIeee) {
        this.txtIeee = txtIeee;
    }

    
    @Column(name="txtPpt", length=500)
    public String getTxtPpt() {
        return this.txtPpt;
    }
    
    public void setTxtPpt(String txtPpt) {
        this.txtPpt = txtPpt;
    }

    
    @Column(name="txtVideo", length=500)
    public String getTxtVideo() {
        return this.txtVideo;
    }
    
    public void setTxtVideo(String txtVideo) {
        this.txtVideo = txtVideo;
    }

    
    @Column(name="txtThesis", length=500)
    public String getTxtThesis() {
        return this.txtThesis;
    }
    
    public void setTxtThesis(String txtThesis) {
        this.txtThesis = txtThesis;
    }

    
    @Column(name="txtFlowDiagram", length=500)
    public String getTxtFlowDiagram() {
        return this.txtFlowDiagram;
    }
    
    public void setTxtFlowDiagram(String txtFlowDiagram) {
        this.txtFlowDiagram = txtFlowDiagram;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtEntryDate", length=19)
    public Date getTxtEntryDate() {
        return this.txtEntryDate;
    }
    
    public void setTxtEntryDate(Date txtEntryDate) {
        this.txtEntryDate = txtEntryDate;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblProject")
    public Set<TblProjectGroup> getTblProjectGroups() {
        return this.tblProjectGroups;
    }
    
    public void setTblProjectGroups(Set<TblProjectGroup> tblProjectGroups) {
        this.tblProjectGroups = tblProjectGroups;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblProject")
    public Set<TblGroupQueriesAnswer> getTblGroupQueriesAnswers() {
        return this.tblGroupQueriesAnswers;
    }
    
    public void setTblGroupQueriesAnswers(Set<TblGroupQueriesAnswer> tblGroupQueriesAnswers) {
        this.tblGroupQueriesAnswers = tblGroupQueriesAnswers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblProject")
    public Set<TblSnapshot> getTblSnapshots() {
        return this.tblSnapshots;
    }
    
    public void setTblSnapshots(Set<TblSnapshot> tblSnapshots) {
        this.tblSnapshots = tblSnapshots;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblProject")
    public Set<TblProjectUpdates> getTblProjectUpdateses() {
        return this.tblProjectUpdateses;
    }
    
    public void setTblProjectUpdateses(Set<TblProjectUpdates> tblProjectUpdateses) {
        this.tblProjectUpdateses = tblProjectUpdateses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblProject")
    public Set<TblGroupAccount> getTblGroupAccounts() {
        return this.tblGroupAccounts;
    }
    
    public void setTblGroupAccounts(Set<TblGroupAccount> tblGroupAccounts) {
        this.tblGroupAccounts = tblGroupAccounts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblProject")
    public Set<TblGroupQueries> getTblGroupQuerieses() {
        return this.tblGroupQuerieses;
    }
    
    public void setTblGroupQuerieses(Set<TblGroupQueries> tblGroupQuerieses) {
        this.tblGroupQuerieses = tblGroupQuerieses;
    }




}


