package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblProjectUpdates generated by hbm2java
 */
@Entity
@Table(name="tbl_project_updates"
    ,catalog="db_manager"
)
public class TblProjectUpdates  implements java.io.Serializable {


     private String txtId;
     private TblProject tblProject;
     private TblProjectGroup tblProjectGroup;
     private String txtDeptId;
     private String txtDescription;
     private String txtAttachmet;
     private Character txtIsActive;

    public TblProjectUpdates() {
    }

	
    public TblProjectUpdates(String txtId, String txtDeptId) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
    }
    public TblProjectUpdates(String txtId, TblProject tblProject, TblProjectGroup tblProjectGroup, String txtDeptId, String txtDescription, String txtAttachmet, Character txtIsActive) {
       this.txtId = txtId;
       this.tblProject = tblProject;
       this.tblProjectGroup = tblProjectGroup;
       this.txtDeptId = txtDeptId;
       this.txtDescription = txtDescription;
       this.txtAttachmet = txtAttachmet;
       this.txtIsActive = txtIsActive;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="txtProjectId")
    public TblProject getTblProject() {
        return this.tblProject;
    }
    
    public void setTblProject(TblProject tblProject) {
        this.tblProject = tblProject;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="txtGroupId")
    public TblProjectGroup getTblProjectGroup() {
        return this.tblProjectGroup;
    }
    
    public void setTblProjectGroup(TblProjectGroup tblProjectGroup) {
        this.tblProjectGroup = tblProjectGroup;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtDescription", length=65535)
    public String getTxtDescription() {
        return this.txtDescription;
    }
    
    public void setTxtDescription(String txtDescription) {
        this.txtDescription = txtDescription;
    }

    
    @Column(name="txtAttachmet", length=65535)
    public String getTxtAttachmet() {
        return this.txtAttachmet;
    }
    
    public void setTxtAttachmet(String txtAttachmet) {
        this.txtAttachmet = txtAttachmet;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


