package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblProjectBug generated by hbm2java
 */
@Entity
@Table(name="tbl_project_bug"
    ,catalog="db_manager"
)
public class TblProjectBug  implements java.io.Serializable {


     private String txtId;
     private TblProjectGroup tblProjectGroup;
     private String txtDeptId;
     private String txtProjectId;
     private String txtModulePath;
     private String txtDescription;
     private String txtAttachment;
     private String txtReplay;
     private String txtRattachment;
     private char txtIsActive;

    public TblProjectBug() {
    }

	
    public TblProjectBug(String txtId, TblProjectGroup tblProjectGroup, String txtDeptId, String txtModulePath, String txtDescription, String txtReplay, char txtIsActive) {
        this.txtId = txtId;
        this.tblProjectGroup = tblProjectGroup;
        this.txtDeptId = txtDeptId;
        this.txtModulePath = txtModulePath;
        this.txtDescription = txtDescription;
        this.txtReplay = txtReplay;
        this.txtIsActive = txtIsActive;
    }
    public TblProjectBug(String txtId, TblProjectGroup tblProjectGroup, String txtDeptId, String txtProjectId, String txtModulePath, String txtDescription, String txtAttachment, String txtReplay, String txtRattachment, char txtIsActive) {
       this.txtId = txtId;
       this.tblProjectGroup = tblProjectGroup;
       this.txtDeptId = txtDeptId;
       this.txtProjectId = txtProjectId;
       this.txtModulePath = txtModulePath;
       this.txtDescription = txtDescription;
       this.txtAttachment = txtAttachment;
       this.txtReplay = txtReplay;
       this.txtRattachment = txtRattachment;
       this.txtIsActive = txtIsActive;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="txtGroupId", nullable=false)
    public TblProjectGroup getTblProjectGroup() {
        return this.tblProjectGroup;
    }
    
    public void setTblProjectGroup(TblProjectGroup tblProjectGroup) {
        this.tblProjectGroup = tblProjectGroup;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtProjectId", length=38)
    public String getTxtProjectId() {
        return this.txtProjectId;
    }
    
    public void setTxtProjectId(String txtProjectId) {
        this.txtProjectId = txtProjectId;
    }

    
    @Column(name="txtModulePath", nullable=false, length=500)
    public String getTxtModulePath() {
        return this.txtModulePath;
    }
    
    public void setTxtModulePath(String txtModulePath) {
        this.txtModulePath = txtModulePath;
    }

    
    @Column(name="txtDescription", nullable=false, length=65535)
    public String getTxtDescription() {
        return this.txtDescription;
    }
    
    public void setTxtDescription(String txtDescription) {
        this.txtDescription = txtDescription;
    }

    
    @Column(name="txtAttachment", length=500)
    public String getTxtAttachment() {
        return this.txtAttachment;
    }
    
    public void setTxtAttachment(String txtAttachment) {
        this.txtAttachment = txtAttachment;
    }

    
    @Column(name="txtReplay", nullable=false, length=500)
    public String getTxtReplay() {
        return this.txtReplay;
    }
    
    public void setTxtReplay(String txtReplay) {
        this.txtReplay = txtReplay;
    }

    
    @Column(name="txtRAttachment", length=500)
    public String getTxtRattachment() {
        return this.txtRattachment;
    }
    
    public void setTxtRattachment(String txtRattachment) {
        this.txtRattachment = txtRattachment;
    }

    
    @Column(name="txtIsActive", nullable=false, length=1)
    public char getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(char txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


