package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblProjectStatus generated by hbm2java
 */
@Entity
@Table(name="tbl_project_status"
    ,catalog="db_manager"
)
public class TblProjectStatus  implements java.io.Serializable {


     private String txtId;
     private TblProjectGroup tblProjectGroup;
     private String txtDeptId;
     private String txtStatusLevel;
     private String txtStatusRemark;
     private String txtStatusAttachment;
     private Date txtEntryDate;
     private Character txtIsActive;

    public TblProjectStatus() {
    }

	
    public TblProjectStatus(String txtId, String txtDeptId, String txtStatusAttachment) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
        this.txtStatusAttachment = txtStatusAttachment;
    }
    public TblProjectStatus(String txtId, TblProjectGroup tblProjectGroup, String txtDeptId, String txtStatusLevel, String txtStatusRemark, String txtStatusAttachment, Date txtEntryDate, Character txtIsActive) {
       this.txtId = txtId;
       this.tblProjectGroup = tblProjectGroup;
       this.txtDeptId = txtDeptId;
       this.txtStatusLevel = txtStatusLevel;
       this.txtStatusRemark = txtStatusRemark;
       this.txtStatusAttachment = txtStatusAttachment;
       this.txtEntryDate = txtEntryDate;
       this.txtIsActive = txtIsActive;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="txtGroupId")
    public TblProjectGroup getTblProjectGroup() {
        return this.tblProjectGroup;
    }
    
    public void setTblProjectGroup(TblProjectGroup tblProjectGroup) {
        this.tblProjectGroup = tblProjectGroup;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtStatusLevel", length=20)
    public String getTxtStatusLevel() {
        return this.txtStatusLevel;
    }
    
    public void setTxtStatusLevel(String txtStatusLevel) {
        this.txtStatusLevel = txtStatusLevel;
    }

    
    @Column(name="txtStatusRemark", length=150)
    public String getTxtStatusRemark() {
        return this.txtStatusRemark;
    }
    
    public void setTxtStatusRemark(String txtStatusRemark) {
        this.txtStatusRemark = txtStatusRemark;
    }

    
    @Column(name="txtStatusAttachment", nullable=false, length=500)
    public String getTxtStatusAttachment() {
        return this.txtStatusAttachment;
    }
    
    public void setTxtStatusAttachment(String txtStatusAttachment) {
        this.txtStatusAttachment = txtStatusAttachment;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtEntryDate", length=19)
    public Date getTxtEntryDate() {
        return this.txtEntryDate;
    }
    
    public void setTxtEntryDate(Date txtEntryDate) {
        this.txtEntryDate = txtEntryDate;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


