package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblProjectInquiry generated by hbm2java
 */
@Entity
@Table(name="tbl_project_inquiry", catalog="db_manager")
public class TblProjectInquiry  implements java.io.Serializable {


     private String txtId;
     private String txtDeptId;
     private String txtProjectCategory;
     private String txtEnquirySubject;
     private String txtTechnologyName;
     private String txtEnquiryType;
     private String txtPassword;
     private String txtStudentName;
     private String txtContactNumber;
     private String txtEmailId;
     private String txtCollegeName;
     private String txtCityName;
     private String txtProjectBudged;
     private String txtEnquiredFrom;
     private Date txtEntryDate;
     private String txtRemark;
     private char txtIsGroup;
     private char txtIsFinal;
     private Character txtIsDelete;
     private Character txtIsActive;
     private Set<TblInquiryTelecalling> tblInquiryTelecallings = new HashSet<TblInquiryTelecalling>(0);
     private Set<TblProjectRequirement> tblProjectRequirements = new HashSet<TblProjectRequirement>(0);
     private Set<TblProjectGroup> tblProjectGroups = new HashSet<TblProjectGroup>(0);

    public TblProjectInquiry() {
    }

	
    public TblProjectInquiry(String txtId, String txtDeptId, String txtProjectCategory, String txtTechnologyName, String txtCollegeName, String txtCityName, String txtProjectBudged, char txtIsGroup, char txtIsFinal) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
        this.txtProjectCategory = txtProjectCategory;
        this.txtTechnologyName = txtTechnologyName;
        this.txtCollegeName = txtCollegeName;
        this.txtCityName = txtCityName;
        this.txtProjectBudged = txtProjectBudged;
        this.txtIsGroup = txtIsGroup;
        this.txtIsFinal = txtIsFinal;
    }
    public TblProjectInquiry(String txtId, String txtDeptId, String txtProjectCategory, String txtEnquirySubject, String txtTechnologyName, String txtEnquiryType, String txtPassword, String txtStudentName, String txtContactNumber, String txtEmailId, String txtCollegeName, String txtCityName, String txtProjectBudged, String txtEnquiredFrom, Date txtEntryDate, String txtRemark, char txtIsGroup, char txtIsFinal, Character txtIsDelete, Character txtIsActive, Set<TblInquiryTelecalling> tblInquiryTelecallings, Set<TblProjectRequirement> tblProjectRequirements, Set<TblProjectGroup> tblProjectGroups) {
       this.txtId = txtId;
       this.txtDeptId = txtDeptId;
       this.txtProjectCategory = txtProjectCategory;
       this.txtEnquirySubject = txtEnquirySubject;
       this.txtTechnologyName = txtTechnologyName;
       this.txtEnquiryType = txtEnquiryType;
       this.txtPassword = txtPassword;
       this.txtStudentName = txtStudentName;
       this.txtContactNumber = txtContactNumber;
       this.txtEmailId = txtEmailId;
       this.txtCollegeName = txtCollegeName;
       this.txtCityName = txtCityName;
       this.txtProjectBudged = txtProjectBudged;
       this.txtEnquiredFrom = txtEnquiredFrom;
       this.txtEntryDate = txtEntryDate;
       this.txtRemark = txtRemark;
       this.txtIsGroup = txtIsGroup;
       this.txtIsFinal = txtIsFinal;
       this.txtIsDelete = txtIsDelete;
       this.txtIsActive = txtIsActive;
       this.tblInquiryTelecallings = tblInquiryTelecallings;
       this.tblProjectRequirements = tblProjectRequirements;
       this.tblProjectGroups = tblProjectGroups;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtProjectCategory", nullable=false, length=38)
    public String getTxtProjectCategory() {
        return this.txtProjectCategory;
    }
    
    public void setTxtProjectCategory(String txtProjectCategory) {
        this.txtProjectCategory = txtProjectCategory;
    }

    
    @Column(name="txtEnquirySubject", length=300)
    public String getTxtEnquirySubject() {
        return this.txtEnquirySubject;
    }
    
    public void setTxtEnquirySubject(String txtEnquirySubject) {
        this.txtEnquirySubject = txtEnquirySubject;
    }

    
    @Column(name="txtTechnologyName", nullable=false, length=30)
    public String getTxtTechnologyName() {
        return this.txtTechnologyName;
    }
    
    public void setTxtTechnologyName(String txtTechnologyName) {
        this.txtTechnologyName = txtTechnologyName;
    }

    
    @Column(name="txtEnquiryType", length=50)
    public String getTxtEnquiryType() {
        return this.txtEnquiryType;
    }
    
    public void setTxtEnquiryType(String txtEnquiryType) {
        this.txtEnquiryType = txtEnquiryType;
    }

    
    @Column(name="txtPassword", length=20)
    public String getTxtPassword() {
        return this.txtPassword;
    }
    
    public void setTxtPassword(String txtPassword) {
        this.txtPassword = txtPassword;
    }

    
    @Column(name="txtStudentName", length=200)
    public String getTxtStudentName() {
        return this.txtStudentName;
    }
    
    public void setTxtStudentName(String txtStudentName) {
        this.txtStudentName = txtStudentName;
    }

    
    @Column(name="txtContactNumber", length=200)
    public String getTxtContactNumber() {
        return this.txtContactNumber;
    }
    
    public void setTxtContactNumber(String txtContactNumber) {
        this.txtContactNumber = txtContactNumber;
    }

    
    @Column(name="txtEmailId", length=200)
    public String getTxtEmailId() {
        return this.txtEmailId;
    }
    
    public void setTxtEmailId(String txtEmailId) {
        this.txtEmailId = txtEmailId;
    }

    
    @Column(name="txtCollegeName", nullable=false, length=30)
    public String getTxtCollegeName() {
        return this.txtCollegeName;
    }
    
    public void setTxtCollegeName(String txtCollegeName) {
        this.txtCollegeName = txtCollegeName;
    }

    
    @Column(name="txtCityName", nullable=false, length=50)
    public String getTxtCityName() {
        return this.txtCityName;
    }
    
    public void setTxtCityName(String txtCityName) {
        this.txtCityName = txtCityName;
    }

    
    @Column(name="txtProjectBudged", nullable=false, length=500)
    public String getTxtProjectBudged() {
        return this.txtProjectBudged;
    }
    
    public void setTxtProjectBudged(String txtProjectBudged) {
        this.txtProjectBudged = txtProjectBudged;
    }

    
    @Column(name="txtEnquiredFrom", length=65535)
    public String getTxtEnquiredFrom() {
        return this.txtEnquiredFrom;
    }
    
    public void setTxtEnquiredFrom(String txtEnquiredFrom) {
        this.txtEnquiredFrom = txtEnquiredFrom;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtEntryDate", length=19)
    public Date getTxtEntryDate() {
        return this.txtEntryDate;
    }
    
    public void setTxtEntryDate(Date txtEntryDate) {
        this.txtEntryDate = txtEntryDate;
    }

    
    @Column(name="txtRemark", length=500)
    public String getTxtRemark() {
        return this.txtRemark;
    }
    
    public void setTxtRemark(String txtRemark) {
        this.txtRemark = txtRemark;
    }

    
    @Column(name="txtIsGroup", nullable=false, length=1)
    public char getTxtIsGroup() {
        return this.txtIsGroup;
    }
    
    public void setTxtIsGroup(char txtIsGroup) {
        this.txtIsGroup = txtIsGroup;
    }

    
    @Column(name="txtIsFinal", nullable=false, length=1)
    public char getTxtIsFinal() {
        return this.txtIsFinal;
    }
    
    public void setTxtIsFinal(char txtIsFinal) {
        this.txtIsFinal = txtIsFinal;
    }

    
    @Column(name="txtIsDelete", length=1)
    public Character getTxtIsDelete() {
        return this.txtIsDelete;
    }
    
    public void setTxtIsDelete(Character txtIsDelete) {
        this.txtIsDelete = txtIsDelete;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblProjectInquiry")
    public Set<TblInquiryTelecalling> getTblInquiryTelecallings() {
        return this.tblInquiryTelecallings;
    }
    
    public void setTblInquiryTelecallings(Set<TblInquiryTelecalling> tblInquiryTelecallings) {
        this.tblInquiryTelecallings = tblInquiryTelecallings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblProjectInquiry")
    public Set<TblProjectRequirement> getTblProjectRequirements() {
        return this.tblProjectRequirements;
    }
    
    public void setTblProjectRequirements(Set<TblProjectRequirement> tblProjectRequirements) {
        this.tblProjectRequirements = tblProjectRequirements;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tblProjectInquiry")
    public Set<TblProjectGroup> getTblProjectGroups() {
        return this.tblProjectGroups;
    }
    
    public void setTblProjectGroups(Set<TblProjectGroup> tblProjectGroups) {
        this.tblProjectGroups = tblProjectGroups;
    }


}


