package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblProjectRegistration generated by hbm2java
 */
@Entity
@Table(name="tbl_project_registration"
    ,catalog="db_manager"
)
public class TblProjectRegistration  implements java.io.Serializable {


     private Integer txtIndex;
     private String txtId;
     private String txtStudentName;
     private String txtEmailId;
     private String txtContactNumber;
     private String txtCollegeName;
     private String txtBranchName;
     private String txtTechnologyName;
     private String txtEnquiredFrom;
     private Character txtIsActive;
     private Date txtEntryDate;

    public TblProjectRegistration() {
    }

	
    public TblProjectRegistration(String txtId, String txtCollegeName, String txtBranchName, String txtTechnologyName) {
        this.txtId = txtId;
        this.txtCollegeName = txtCollegeName;
        this.txtBranchName = txtBranchName;
        this.txtTechnologyName = txtTechnologyName;
    }
    public TblProjectRegistration(String txtId, String txtStudentName, String txtEmailId, String txtContactNumber, String txtCollegeName, String txtBranchName, String txtTechnologyName, String txtEnquiredFrom, Character txtIsActive, Date txtEntryDate) {
       this.txtId = txtId;
       this.txtStudentName = txtStudentName;
       this.txtEmailId = txtEmailId;
       this.txtContactNumber = txtContactNumber;
       this.txtCollegeName = txtCollegeName;
       this.txtBranchName = txtBranchName;
       this.txtTechnologyName = txtTechnologyName;
       this.txtEnquiredFrom = txtEnquiredFrom;
       this.txtIsActive = txtIsActive;
       this.txtEntryDate = txtEntryDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="txtIndex", unique=true, nullable=false)
    public Integer getTxtIndex() {
        return this.txtIndex;
    }
    
    public void setTxtIndex(Integer txtIndex) {
        this.txtIndex = txtIndex;
    }

    
    @Column(name="txtId", nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

    
    @Column(name="txtStudentName", length=200)
    public String getTxtStudentName() {
        return this.txtStudentName;
    }
    
    public void setTxtStudentName(String txtStudentName) {
        this.txtStudentName = txtStudentName;
    }

    
    @Column(name="txtEmailId", length=200)
    public String getTxtEmailId() {
        return this.txtEmailId;
    }
    
    public void setTxtEmailId(String txtEmailId) {
        this.txtEmailId = txtEmailId;
    }

    
    @Column(name="txtContactNumber", length=200)
    public String getTxtContactNumber() {
        return this.txtContactNumber;
    }
    
    public void setTxtContactNumber(String txtContactNumber) {
        this.txtContactNumber = txtContactNumber;
    }

    
    @Column(name="txtCollegeName", nullable=false, length=30)
    public String getTxtCollegeName() {
        return this.txtCollegeName;
    }
    
    public void setTxtCollegeName(String txtCollegeName) {
        this.txtCollegeName = txtCollegeName;
    }

    
    @Column(name="txtBranchName", nullable=false, length=30)
    public String getTxtBranchName() {
        return this.txtBranchName;
    }
    
    public void setTxtBranchName(String txtBranchName) {
        this.txtBranchName = txtBranchName;
    }

    
    @Column(name="txtTechnologyName", nullable=false, length=30)
    public String getTxtTechnologyName() {
        return this.txtTechnologyName;
    }
    
    public void setTxtTechnologyName(String txtTechnologyName) {
        this.txtTechnologyName = txtTechnologyName;
    }

    
    @Column(name="txtEnquiredFrom", length=65535)
    public String getTxtEnquiredFrom() {
        return this.txtEnquiredFrom;
    }
    
    public void setTxtEnquiredFrom(String txtEnquiredFrom) {
        this.txtEnquiredFrom = txtEnquiredFrom;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtEntryDate", length=19)
    public Date getTxtEntryDate() {
        return this.txtEntryDate;
    }
    
    public void setTxtEntryDate(Date txtEntryDate) {
        this.txtEntryDate = txtEntryDate;
    }




}


