package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblTallychart1 generated by hbm2java
 */
@Entity
@Table(name="tbl_tallychart_1"
    ,catalog="db_manager"
)
public class TblTallychart1  implements java.io.Serializable {


     private String txtId;
     private String txtDeptId;
     private String txtOtherId;
     private String txtOrgId;
     private String txtTransactionType;
     private String txtPersonName;
     private Integer txtAmount;
     private String txtDescription;
     private String txtFromIp;
     private Date txtEntryDate;
     private String txtEnteredBy;
     private Date txtUpdateDate;
     private String txtUpdateBy;
     private Character txtIsDelete;
     private Character txtIsActive;

    public TblTallychart1() {
    }

	
    public TblTallychart1(String txtId, String txtDeptId, String txtOtherId, String txtTransactionType) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
        this.txtOtherId = txtOtherId;
        this.txtTransactionType = txtTransactionType;
    }
    public TblTallychart1(String txtId, String txtDeptId, String txtOtherId, String txtOrgId, String txtTransactionType, String txtPersonName, Integer txtAmount, String txtDescription, String txtFromIp, Date txtEntryDate, String txtEnteredBy, Date txtUpdateDate, String txtUpdateBy, Character txtIsDelete, Character txtIsActive) {
       this.txtId = txtId;
       this.txtDeptId = txtDeptId;
       this.txtOtherId = txtOtherId;
       this.txtOrgId = txtOrgId;
       this.txtTransactionType = txtTransactionType;
       this.txtPersonName = txtPersonName;
       this.txtAmount = txtAmount;
       this.txtDescription = txtDescription;
       this.txtFromIp = txtFromIp;
       this.txtEntryDate = txtEntryDate;
       this.txtEnteredBy = txtEnteredBy;
       this.txtUpdateDate = txtUpdateDate;
       this.txtUpdateBy = txtUpdateBy;
       this.txtIsDelete = txtIsDelete;
       this.txtIsActive = txtIsActive;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtOtherId", nullable=false, length=38)
    public String getTxtOtherId() {
        return this.txtOtherId;
    }
    
    public void setTxtOtherId(String txtOtherId) {
        this.txtOtherId = txtOtherId;
    }

    
    @Column(name="txtOrgId", length=38)
    public String getTxtOrgId() {
        return this.txtOrgId;
    }
    
    public void setTxtOrgId(String txtOrgId) {
        this.txtOrgId = txtOrgId;
    }

    
    @Column(name="txtTransactionType", nullable=false, length=10)
    public String getTxtTransactionType() {
        return this.txtTransactionType;
    }
    
    public void setTxtTransactionType(String txtTransactionType) {
        this.txtTransactionType = txtTransactionType;
    }

    
    @Column(name="txtPersonName", length=100)
    public String getTxtPersonName() {
        return this.txtPersonName;
    }
    
    public void setTxtPersonName(String txtPersonName) {
        this.txtPersonName = txtPersonName;
    }

    
    @Column(name="txtAmount")
    public Integer getTxtAmount() {
        return this.txtAmount;
    }
    
    public void setTxtAmount(Integer txtAmount) {
        this.txtAmount = txtAmount;
    }

    
    @Column(name="txtDescription", length=65535)
    public String getTxtDescription() {
        return this.txtDescription;
    }
    
    public void setTxtDescription(String txtDescription) {
        this.txtDescription = txtDescription;
    }

    
    @Column(name="txtFromIp", length=15)
    public String getTxtFromIp() {
        return this.txtFromIp;
    }
    
    public void setTxtFromIp(String txtFromIp) {
        this.txtFromIp = txtFromIp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtEntryDate", length=19)
    public Date getTxtEntryDate() {
        return this.txtEntryDate;
    }
    
    public void setTxtEntryDate(Date txtEntryDate) {
        this.txtEntryDate = txtEntryDate;
    }

    
    @Column(name="txtEnteredBy", length=38)
    public String getTxtEnteredBy() {
        return this.txtEnteredBy;
    }
    
    public void setTxtEnteredBy(String txtEnteredBy) {
        this.txtEnteredBy = txtEnteredBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtUpdateDate", length=19)
    public Date getTxtUpdateDate() {
        return this.txtUpdateDate;
    }
    
    public void setTxtUpdateDate(Date txtUpdateDate) {
        this.txtUpdateDate = txtUpdateDate;
    }

    
    @Column(name="txtUpdateBy", length=38)
    public String getTxtUpdateBy() {
        return this.txtUpdateBy;
    }
    
    public void setTxtUpdateBy(String txtUpdateBy) {
        this.txtUpdateBy = txtUpdateBy;
    }

    
    @Column(name="txtIsDelete", length=1)
    public Character getTxtIsDelete() {
        return this.txtIsDelete;
    }
    
    public void setTxtIsDelete(Character txtIsDelete) {
        this.txtIsDelete = txtIsDelete;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


