package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblTallychart29082015 generated by hbm2java
 */
@Entity
@Table(name="tbl_tallychart_29_08_2015"
    ,catalog="db_manager"
)
public class TblTallychart29082015  implements java.io.Serializable {


     private String txtId;
     private String txtDeptId;
     private String txtTransactionType;
     private String txtPersonName;
     private Integer txtAmount;
     private String txtDescription;
     private Date txtEntryDate;
     private String txtEnteredBy;
     private Character txtIsDelete;
     private Character txtIsActive;

    public TblTallychart29082015() {
    }

	
    public TblTallychart29082015(String txtId, String txtDeptId, String txtTransactionType) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
        this.txtTransactionType = txtTransactionType;
    }
    public TblTallychart29082015(String txtId, String txtDeptId, String txtTransactionType, String txtPersonName, Integer txtAmount, String txtDescription, Date txtEntryDate, String txtEnteredBy, Character txtIsDelete, Character txtIsActive) {
       this.txtId = txtId;
       this.txtDeptId = txtDeptId;
       this.txtTransactionType = txtTransactionType;
       this.txtPersonName = txtPersonName;
       this.txtAmount = txtAmount;
       this.txtDescription = txtDescription;
       this.txtEntryDate = txtEntryDate;
       this.txtEnteredBy = txtEnteredBy;
       this.txtIsDelete = txtIsDelete;
       this.txtIsActive = txtIsActive;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtTransactionType", nullable=false, length=10)
    public String getTxtTransactionType() {
        return this.txtTransactionType;
    }
    
    public void setTxtTransactionType(String txtTransactionType) {
        this.txtTransactionType = txtTransactionType;
    }

    
    @Column(name="txtPersonName", length=100)
    public String getTxtPersonName() {
        return this.txtPersonName;
    }
    
    public void setTxtPersonName(String txtPersonName) {
        this.txtPersonName = txtPersonName;
    }

    
    @Column(name="txtAmount")
    public Integer getTxtAmount() {
        return this.txtAmount;
    }
    
    public void setTxtAmount(Integer txtAmount) {
        this.txtAmount = txtAmount;
    }

    
    @Column(name="txtDescription", length=65535)
    public String getTxtDescription() {
        return this.txtDescription;
    }
    
    public void setTxtDescription(String txtDescription) {
        this.txtDescription = txtDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtEntryDate", length=19)
    public Date getTxtEntryDate() {
        return this.txtEntryDate;
    }
    
    public void setTxtEntryDate(Date txtEntryDate) {
        this.txtEntryDate = txtEntryDate;
    }

    
    @Column(name="txtEnteredBy", length=38)
    public String getTxtEnteredBy() {
        return this.txtEnteredBy;
    }
    
    public void setTxtEnteredBy(String txtEnteredBy) {
        this.txtEnteredBy = txtEnteredBy;
    }

    
    @Column(name="txtIsDelete", length=1)
    public Character getTxtIsDelete() {
        return this.txtIsDelete;
    }
    
    public void setTxtIsDelete(Character txtIsDelete) {
        this.txtIsDelete = txtIsDelete;
    }

    
    @Column(name="txtIsActive", length=1)
    public Character getTxtIsActive() {
        return this.txtIsActive;
    }
    
    public void setTxtIsActive(Character txtIsActive) {
        this.txtIsActive = txtIsActive;
    }




}


