package com.main.pojo;
// Generated Dec 6, 2016 11:51:12 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblWorklog generated by hbm2java
 */
@Entity
@Table(name="tbl_worklog"
    ,catalog="db_manager"
)
public class TblWorklog  implements java.io.Serializable {


     private String txtId;
     private String txtDeptId;
     private String txtOtherPk;
     private String txtFromSection;
     private String txtFromMenu;
     private String txtDescription;
     private Date txtEntryDateDate;

    public TblWorklog() {
    }

	
    public TblWorklog(String txtId, String txtDeptId, String txtOtherPk) {
        this.txtId = txtId;
        this.txtDeptId = txtDeptId;
        this.txtOtherPk = txtOtherPk;
    }
    public TblWorklog(String txtId, String txtDeptId, String txtOtherPk, String txtFromSection, String txtFromMenu, String txtDescription, Date txtEntryDateDate) {
       this.txtId = txtId;
       this.txtDeptId = txtDeptId;
       this.txtOtherPk = txtOtherPk;
       this.txtFromSection = txtFromSection;
       this.txtFromMenu = txtFromMenu;
       this.txtDescription = txtDescription;
       this.txtEntryDateDate = txtEntryDateDate;
    }
   
     @Id 

    
    @Column(name="txtId", unique=true, nullable=false, length=38)
    public String getTxtId() {
        return this.txtId;
    }
    
    public void setTxtId(String txtId) {
        this.txtId = txtId;
    }

    
    @Column(name="txtDeptId", nullable=false, length=38)
    public String getTxtDeptId() {
        return this.txtDeptId;
    }
    
    public void setTxtDeptId(String txtDeptId) {
        this.txtDeptId = txtDeptId;
    }

    
    @Column(name="txtOtherPk", nullable=false, length=38)
    public String getTxtOtherPk() {
        return this.txtOtherPk;
    }
    
    public void setTxtOtherPk(String txtOtherPk) {
        this.txtOtherPk = txtOtherPk;
    }

    
    @Column(name="txtFromSection", length=50)
    public String getTxtFromSection() {
        return this.txtFromSection;
    }
    
    public void setTxtFromSection(String txtFromSection) {
        this.txtFromSection = txtFromSection;
    }

    
    @Column(name="txtFromMenu", length=50)
    public String getTxtFromMenu() {
        return this.txtFromMenu;
    }
    
    public void setTxtFromMenu(String txtFromMenu) {
        this.txtFromMenu = txtFromMenu;
    }

    
    @Column(name="txtDescription", length=65535)
    public String getTxtDescription() {
        return this.txtDescription;
    }
    
    public void setTxtDescription(String txtDescription) {
        this.txtDescription = txtDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="txtEntryDateDate", length=19)
    public Date getTxtEntryDateDate() {
        return this.txtEntryDateDate;
    }
    
    public void setTxtEntryDateDate(Date txtEntryDateDate) {
        this.txtEntryDateDate = txtEntryDateDate;
    }




}


